GET http://127.0.0.1:3001/api/persons

###

POST http://127.0.0.1:3001/api/persons
Content-Type: application/json

{
    "name" : "Ilia G",
    "number" : "123-456"
}

###

PUT http://127.0.0.1:3001/api/persons/63bc4f2ea915aa3fbee85a1f
Content-Type: application/json

{
    "name" : "Ilia G",
    "number" : "123-998"
}

###

GET http://127.0.0.1:3001/info

###
GET http://127.0.0.1:3001/api/persons/63bc4f2ea915aa3fbee85a1f

###
GET http://127.0.0.1:3001/api/persons/67576

###
DELETE http://127.0.0.1:3001/api/persons/63bc5da84f9e7dc91e42e2ed